# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.22.1'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
arr = np.zeros(10)

arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [5]:
np.size(arr)

10

In [8]:
arr.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
# Creating null vector
arr = np.zeros(10)
# assign 1 to fifth element
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [13]:
print(arr)
print(arr[::-1])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [14]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [15]:
lst = [1,2,0,0,4,0]

np.nonzero(lst)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [19]:
np.random.uniform((3,3,3))

array([1.18406912, 1.53951471, 1.72275106])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [21]:
arr = np.random.random((10,10))

arrmin, arrmax = arr.min(), arr.max()

print("Maximum Value: ", arrmax)
print('Minimum Value: ', arrmin)

Maximum Value:  0.9836391385487979
Minimum Value:  0.03075542362379957


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [24]:
arr = np.random.random(30)
arr.mean()

0.47048165639034

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [28]:
arr = np.ones((10,10))

arr[1:-1, 1:-1] = 0

arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [42]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [43]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [45]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [8]:
arr = np.zeros((8,8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [9]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [11]:
arr = np.array([[0,1], [1,0]])
arr = np.tile(arr, (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [12]:
arr = np.random.random((5,5))

arr = (arr - arr.min()) / (arr.max() - arr.min())

arr

array([[0.68259296, 0.30388901, 0.0279266 , 0.53149772, 0.36405453],
       [0.        , 0.95193338, 0.43620355, 0.40301959, 0.83677743],
       [0.26846706, 0.65454399, 0.68268218, 0.57077294, 0.89136434],
       [0.50182053, 0.94127402, 0.63915487, 0.98658081, 0.48127546],
       [1.        , 0.60275352, 0.83802891, 0.12302533, 0.27262986]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [13]:
np.dtype([
    ('r', np.ubyte, 1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1)
])

/tmp/ipykernel_8614/2055069237.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.dtype([


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [14]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [15]:
# or
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [16]:
arr = np.arange(11)

arr[(3<arr) & (arr <=8)] *= -1

arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [17]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [23]:
Z = np.ones(3, dtype=int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[1 1 1]
[1 1 1]
[False False False]
[0.+1.j 0.+1.j 0.+1.j]
[1. 1. 1.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
nan
[-9.22337204e+18]


/tmp/ipykernel_8614/43632603.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_8614/43632603.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [25]:
arr = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-9. -2. -5. -4. -7. -9. -3. -4. 10.  3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [26]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10, 10)
print(np.intersect1d(arr1, arr2))

[0 1 2 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all = 'ignore')



#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [27]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_8614/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [29]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1,'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1,'D')

print('Yesterday: ', yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2022-02-11
Today:  2022-02-12
Tomorrow:  2022-02-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [31]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]').tolist()

[datetime.date(2016, 7, 1),
 datetime.date(2016, 7, 2),
 datetime.date(2016, 7, 3),
 datetime.date(2016, 7, 4),
 datetime.date(2016, 7, 5),
 datetime.date(2016, 7, 6),
 datetime.date(2016, 7, 7),
 datetime.date(2016, 7, 8),
 datetime.date(2016, 7, 9),
 datetime.date(2016, 7, 10),
 datetime.date(2016, 7, 11),
 datetime.date(2016, 7, 12),
 datetime.date(2016, 7, 13),
 datetime.date(2016, 7, 14),
 datetime.date(2016, 7, 15),
 datetime.date(2016, 7, 16),
 datetime.date(2016, 7, 17),
 datetime.date(2016, 7, 18),
 datetime.date(2016, 7, 19),
 datetime.date(2016, 7, 20),
 datetime.date(2016, 7, 21),
 datetime.date(2016, 7, 22),
 datetime.date(2016, 7, 23),
 datetime.date(2016, 7, 24),
 datetime.date(2016, 7, 25),
 datetime.date(2016, 7, 26),
 datetime.date(2016, 7, 27),
 datetime.date(2016, 7, 28),
 datetime.date(2016, 7, 29),
 datetime.date(2016, 7, 30),
 datetime.date(2016, 7, 31)]

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [33]:
A = np.ones(5) * 1
B = np.ones(5) * 2
C = np.ones(5) * 3

np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [38]:
arr = np.random.uniform(1,10,10)

# using % 
print(arr - arr%1)

# using floor()
print(np.floor(arr))

# using ceil()
print(np.ceil(arr)-1)

# using astype()
print(arr.astype(int))

# using trunc function
print(np.trunc(arr))

[3. 2. 4. 5. 6. 1. 6. 4. 6. 8.]
[3. 2. 4. 5. 6. 1. 6. 4. 6. 8.]
[3. 2. 4. 5. 6. 1. 6. 4. 6. 8.]
[3 2 4 5 6 1 6 4 6 8]
[3. 2. 4. 5. 6. 1. 6. 4. 6. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [39]:
arr = np.zeros((5,5))

arr = arr + np.arange(5)

arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [42]:
def generator():
    for x in range(10):
        yield x


np.fromiter(generator(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [45]:
np.linspace(0,1,12, endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [46]:
arr = np.random.random(10)
arr.sort()
arr

array([0.07565334, 0.1703312 , 0.17850702, 0.25242525, 0.35124427,
       0.40360665, 0.67330728, 0.68495898, 0.7723695 , 0.97014945])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [48]:
arr = np.arange(15)
print(arr)
np.add.reduce(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


105

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [55]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)

print(np.allclose(A,B))

print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [57]:
arr = np.ones(5, dtype=int)
arr.flags.writeable=False
print(arr)
arr[1] = 0 

[1 1 1 1 1]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### Note:

- In cartesian coordinates, there is exactly one set of coordinates for any given point.
- In polar coordinates, there is literally an infinite number of coordinates for a given point.



In [60]:
arr = np.random.random((10,2))
print("original array:\n",arr)

x,y = arr[:,0], arr[:,1]
print('')
print(x)
print(y)

A = np.sqrt(x**2 + y** 2)
B = np.arctan2(y,x)
print('')
print(A)
print(B)



original array:
 [[0.22522948 0.21934131]
 [0.59338825 0.45900841]
 [0.78173983 0.94342402]
 [0.83075799 0.49630673]
 [0.50566776 0.48491346]
 [0.24998324 0.86840885]
 [0.38657671 0.23927121]
 [0.96329345 0.48190285]
 [0.19408451 0.02728577]
 [0.67339217 0.5521332 ]]

[0.22522948 0.59338825 0.78173983 0.83075799 0.50566776 0.24998324
 0.38657671 0.96329345 0.19408451 0.67339217]
[0.21934131 0.45900841 0.94342402 0.49630673 0.48491346 0.86840885
 0.23927121 0.48190285 0.02728577 0.5521332 ]

[0.31438659 0.75019886 1.22522082 0.96771856 0.70060042 0.90367336
 0.45463421 1.07710939 0.19599314 0.87080887]
[0.77215431 0.65839608 0.87884626 0.53851611 0.76444959 1.29051075
 0.55423609 0.4638603  0.13967168 0.68677469]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [63]:
arr = np.random.rand(10)
print('Original array:\n',arr)
arr[arr.argmax()] = 0
print('Altered array:\n',arr)

Original array:
 [0.03895126 0.69805708 0.66912974 0.09985579 0.2850891  0.9949433
 0.44867215 0.55063407 0.87758566 0.21077154]
Altered array:
 [0.03895126 0.69805708 0.66912974 0.09985579 0.2850891  0.
 0.44867215 0.55063407 0.87758566 0.21077154]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [1]:
import numpy as np

arr = np.zeros((10,10), [('x', float), ('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))

arr

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [2]:
X = np.arange(8)
Y = X + 0.5

C = 1 /np.subtract.outer(X,Y)

np.linalg.det(C)

3638.163637117973

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [3]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [8]:
np.set_printoptions()

arr = np.zeros((10,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [10]:
arr = np.arange(100)
X = np.random.uniform(0,100)
v = (np.abs(arr-X)).argmin()

arr[v]

72

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [11]:
arr = np.zeros(
    10,
    [
        ('position', [
            ('x', float, 1),
            ('y', float, 1)
        ]),
        ('color', [
            ('r', float, 1),
            ('g', float, 1),
            ('b', float, 1)
        ])
    ]
)

arr

/tmp/ipykernel_180217/1463489313.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [12]:
arr = np.random.random((100,2))

X,Y = np.atleast_2d(arr[:,0], arr[:,1])

distance = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)

distance

array([[0.        , 0.32261113, 0.47464093, ..., 0.50228198, 0.60624287,
        0.86107157],
       [0.32261113, 0.        , 0.39553281, ..., 0.79441069, 0.71534384,
        0.92133397],
       [0.47464093, 0.39553281, 0.        , ..., 0.70499713, 0.39198527,
        0.54302044],
       ...,
       [0.50228198, 0.79441069, 0.70499713, ..., 0.        , 0.49549302,
        0.72833149],
       [0.60624287, 0.71534384, 0.39198527, ..., 0.49549302, 0.        ,
        0.26422877],
       [0.86107157, 0.92133397, 0.54302044, ..., 0.72833149, 0.26422877,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [15]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [17]:
from io import StringIO

s = StringIO(
    """
    1,2,3,4,5\n
    6, , ,7,8\n
    , , 9, 10, 11\n"""
)

arr = np.genfromtxt(s, delimiter=',', dtype=np.int)

print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/tmp/ipykernel_180217/1375898314.py:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.genfromtxt(s, delimiter=',', dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [18]:
arr = np.arange(10).reshape(2,5)

arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
for i,v in np.ndenumerate(arr):
    print(i,v)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


In [20]:
for i in np.ndindex(arr.shape):
    print(i, arr[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [21]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
S = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0

np.exp(-((S-mu)**2 / (2.0 * sigma**2)))

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [24]:
arr = np.zeros((5,5))

p = 4

np.put(arr, np.random.choice(range(5*5), p, replace=False), 1)

arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [29]:
X = np.random.rand(4,5)

Y = X - X.mean(axis=1, keepdims=True)

Y


array([[-0.23614437, -0.10457549, -0.02635501,  0.51699024, -0.14991537],
       [-0.40021592,  0.02780671,  0.12815643,  0.17974304,  0.06450975],
       [ 0.40452191, -0.10731905,  0.314076  , -0.28814931, -0.32312954],
       [-0.27442363, -0.28207703,  0.27841736,  0.14192401,  0.13615928]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [34]:
arr = np.random.randint(0,20,(5,4))
print("Original Array:\n",arr)


print("\nSorted Array:\n",arr[arr[:,1].argsort()])

Original Array:
 [[ 1 10  8 18]
 [ 7  8  9 15]
 [18  5 11 13]
 [ 8 14  3  9]
 [14 10 11 11]]

Sorted Array:
 [[18  5 11 13]
 [ 7  8  9 15]
 [ 1 10  8 18]
 [14 10 11 11]
 [ 8 14  3  9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [36]:
arr = np.random.randint(0,3,(3,10))
print('Original 2D Array:', arr)

print("Is there any null values: ",(~arr.any(axis=0)).any())

Original 2D Array: [[2 0 1 1 2 2 0 2 1 0]
 [1 1 2 1 1 0 1 0 0 2]
 [1 2 0 2 1 1 2 0 2 0]]
Is there any null values:  False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [47]:
arr = np.random.uniform(0,1,8)
print('Original array', arr)

x = 0.3

nearest = arr.flat[np.abs(arr-x).argmin()]
print("Nearest value to 0.3",nearest)

Original array [0.18027097 0.48317827 0.55980236 0.22659592 0.67951006 0.7932634
 0.51156877 0.10278384]
Nearest value to 0.3 0.22659592188571354


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [49]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

iter = np.nditer([A,B, None])

for x,y,z in iter:
    z[...] = x+y

print(iter.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [1]:
import numpy as np


class Array(np.ndarray):
    def __new__(cls, array, name='no name'):
        obj = np.asanyarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', 'no name')

arr = Array(np.arange(10), "range_10")
print(arr.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [4]:
arr = np.ones(10)
print(arr)
X = np.random.randint(0, len(arr), 20)
arr += np.bincount(X, minlength=len(arr))
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 5. 5. 1. 2. 1. 2. 5. 3. 4.]


In [5]:
# or

np.add.at(arr,X,1)
print(arr)

[3. 9. 9. 1. 3. 1. 3. 9. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [8]:
A = [1,2,3,4,5,6]
B = [7,8,9,10,11,12]

arr = np.bincount(B,A)
arr

array([0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [9]:
w,h = 16,16

A = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = A[...,0]*(256*256) + A[...,1]*256 + A[...,2]

n_unique = len(np.unique(F))
n_unique

8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [12]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[4 2 9 1]
   [6 6 5 4]
   [7 7 4 8]]

  [[6 4 7 7]
   [6 9 6 2]
   [8 8 3 2]]

  [[4 5 5 3]
   [8 6 3 1]
   [5 0 2 3]]

  [[2 0 4 6]
   [8 2 7 9]
   [1 1 0 3]]]


 [[[5 0 5 0]
   [2 1 3 1]
   [5 5 4 6]]

  [[0 1 3 5]
   [3 8 6 7]
   [3 2 4 6]]

  [[9 5 5 7]
   [6 0 0 9]
   [3 1 6 8]]

  [[5 5 5 8]
   [9 7 5 6]
   [5 3 7 3]]]


 [[[6 0 3 1]
   [7 7 6 1]
   [1 7 5 7]]

  [[6 9 5 0]
   [2 1 9 2]
   [8 4 9 7]]

  [[0 2 3 5]
   [1 9 8 9]
   [0 1 1 6]]

  [[7 7 5 3]
   [9 8 7 8]
   [2 9 6 1]]]]
[[63 68 45 43]
 [37 48 59 68]
 [51 62 45 72]]
[[63 68 45 43]
 [37 48 59 68]
 [51 62 45 72]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [14]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)



[0.51056388 0.61622275 0.54119407 0.55438974 0.47593524 0.36866507
 0.53194541 0.47551402 0.54533745 0.46588113]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [17]:
X = np.random.random((5,5))
Y = np.random.random((5,5))

print(np.diag(np.dot(X,Y)))


[1.13778645 1.30846468 0.4162287  1.43902256 1.37483543]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [19]:
arr = np.array([1,2,3,4,5])
# print(arr)
n = 3
arr0 = np.zeros(len(arr) + (len(arr)-1)*n)
arr0[::n+1] = arr
print(arr0)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [26]:
X = 2*np.ones((5,5,3))
Y = 3**np.ones((5,5))
X*Y[:,:,None]

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [29]:
A = np.arange(10).reshape(5,2)
print('Original A:\n',A)
A[[0,1]] = A[[1,0]]
print('Altered array:\n',A)

Original A:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Altered array:
 [[2 3]
 [0 1]
 [4 5]
 [6 7]
 [8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [5]:
import numpy as np

sides = np.random.randint(0,100, (10,3))
x = np.roll(sides.repeat(2,axis=1), -1, axis=1)
x = x.reshape(len(x)*3,2)
x = np.sort(x,axis=1)

ls = x.view(dtype=[('p0', x.dtype),('p1', x.dtype)])
ls = np.unique(ls)
print(ls)

[( 0,  8) ( 0, 86) ( 2, 36) ( 2, 43) ( 8, 86) ( 9, 12) ( 9, 53) (10, 62)
 (10, 74) (11, 23) (11, 35) (12, 53) (16, 27) (16, 80) (23, 25) (23, 26)
 (23, 35) (23, 75) (23, 97) (25, 75) (26, 97) (27, 67) (27, 80) (27, 97)
 (36, 43) (43, 65) (43, 96) (62, 74) (65, 96) (67, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [7]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [8]:
def average(arr,n):
    avg = np.cumsum(arr, dtype=float)
    avg[n:] = avg[n:] - avg[:-n]
    return avg[n-1:]/n

arr = np.arange(20)
average(arr,n=3)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [4]:
import numpy as np
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

arr = rolling(np.arange(10), 3)

print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [5]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

arr = np.random.uniform(-1.0, 1.0, 100)
np.negative(arr, out=arr)

array([ 0.56548067, -0.01773852, -0.15663125,  0.29869145,  0.35469249,
        0.11666761,  0.2184294 ,  0.25101891,  0.58741828, -0.62978003,
        0.8056257 ,  0.81810472,  0.55894992, -0.67306481,  0.1849043 ,
        0.6886183 , -0.74552589, -0.91800026, -0.22297441,  0.68026888,
        0.06486114,  0.20942242,  0.98816828, -0.30842157,  0.63174791,
        0.63982502,  0.81069293,  0.25386028,  0.05839434,  0.15126131,
       -0.25147879, -0.01654149, -0.82276229,  0.20813505,  0.04090113,
       -0.98345717, -0.16696706, -0.53072657, -0.88058334, -0.51435928,
        0.20973994, -0.83229778, -0.95520413, -0.70650156,  0.19108959,
       -0.81214209,  0.37293722, -0.6755497 ,  0.96378874, -0.99125226,
       -0.89083328, -0.86815258,  0.02710436, -0.36999727,  0.55193855,
        0.07108641,  0.27350501, -0.71933333,  0.41105194, -0.16584256,
       -0.43990079, -0.66982705, -0.12073772, -0.0387819 , -0.36076481,
        0.87142488, -0.66183253,  0.23540567, -0.03922834,  0.49

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [6]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T ** 2).sum(axis=1)
    U = -((P0[:,0]-p[...,0]) * T[:,0] + (P0[:,1]-p[...,1]) * T[:,1]) /L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform(-10, 10, (1,2))
print(distance(P0, P1, p))

[ 7.35406316  4.37616974 13.39724195  2.76936633  3.27564936  0.65253863
 14.80862763 13.53938633  9.80631636  7.78102139]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [7]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0, P1, i) for i in p]))

[[9.31528884e-02 3.06030162e+00 4.93702354e-01 4.29851157e+00
  2.91130675e+00 4.88313827e+00 8.93933020e-01 4.89916342e+00
  3.07088629e+00 2.35521509e+00]
 [4.47716986e+00 4.95991569e+00 3.70874296e+00 6.32148208e-01
  2.06801624e+00 8.28649411e+00 4.50122944e+00 1.49753000e-02
  2.33215002e+00 2.82670811e+00]
 [9.88423732e-01 3.99209537e+00 1.17947354e+01 5.58276264e-01
  1.48984884e+00 1.43779957e+00 1.19188417e+01 1.64213927e+00
  1.20755513e+01 7.01779586e+00]
 [6.62841218e+00 5.62964617e-01 1.42379378e+01 5.15422582e+00
  7.16848775e+00 6.25243409e+00 1.48994632e+01 4.08130544e+00
  9.83639334e+00 5.06430496e+00]
 [2.95256335e+00 5.27562166e+00 1.30234842e+00 1.33833255e+00
  8.82159914e-04 7.68912023e+00 2.01067505e+00 1.91019352e+00
  1.41689018e+00 3.86972886e+00]
 [1.44140083e+01 7.72964838e+00 1.26103046e+01 1.18191003e+01
  1.34785373e+01 1.49152580e+01 1.41887303e+01 1.09853050e+01
  2.39061970e+00 2.13186744e+00]
 [1.49411909e+00 1.05667664e+00 4.47438095e+00 4.59743663e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [10]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 3 8 2 0 4 0 4 0 2]
 [8 2 3 4 1 5 8 1 5 2]
 [1 2 4 8 7 9 2 1 1 5]
 [2 3 5 2 9 6 7 2 9 0]
 [0 3 8 7 8 4 5 0 9 7]
 [5 5 5 5 5 5 6 5 5 7]
 [6 7 8 9 5 8 9 3 5 3]
 [7 5 4 7 7 3 6 3 4 9]
 [5 8 1 2 8 6 6 6 1 0]
 [3 9 9 5 7 0 1 8 9 7]]
[[0 0 0 0 0]
 [0 5 3 8 2]
 [0 8 2 3 4]
 [0 1 2 4 8]
 [0 2 3 5 2]]


/tmp/ipykernel_23381/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [12]:
arr = np.arange(1, 15, dtype=np.uint32)
new_arr = stride_tricks.as_strided(arr, (11,4), (4,4))
print(new_arr)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [13]:
arr = np.random.uniform(0,1, (10,10))
a,b,c = np.linalg.svd(arr) # Singular Value Decomposition
rank = np.sum(b>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [14]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [15]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1] - 3)

n_arr = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
n_arr

array([[[[2, 3, 0],
         [1, 0, 2],
         [1, 4, 3]],

        [[3, 0, 0],
         [0, 2, 0],
         [4, 3, 4]],

        [[0, 0, 0],
         [2, 0, 4],
         [3, 4, 1]],

        [[0, 0, 1],
         [0, 4, 4],
         [4, 1, 4]],

        [[0, 1, 2],
         [4, 4, 3],
         [1, 4, 2]],

        [[1, 2, 3],
         [4, 3, 3],
         [4, 2, 3]],

        [[2, 3, 1],
         [3, 3, 2],
         [2, 3, 2]],

        [[3, 1, 1],
         [3, 2, 4],
         [3, 2, 1]]],


       [[[1, 0, 2],
         [1, 4, 3],
         [1, 4, 3]],

        [[0, 2, 0],
         [4, 3, 4],
         [4, 3, 0]],

        [[2, 0, 4],
         [3, 4, 1],
         [3, 0, 0]],

        [[0, 4, 4],
         [4, 1, 4],
         [0, 0, 4]],

        [[4, 4, 3],
         [1, 4, 2],
         [0, 4, 2]],

        [[4, 3, 3],
         [4, 2, 3],
         [4, 2, 0]],

        [[3, 3, 2],
         [2, 3, 2],
         [2, 0, 1]],

        [[3, 2, 4],
         [3, 2, 1],
         [0, 1, 2]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [21]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

def symetric(arr):
    return np.asarray(arr + arr.T - np.diag(arr.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 17  4  8 11]
 [17  6  2 11  2]
 [ 4  2  9 42  1]
 [ 8 11 42  9 13]
 [11  2  1 13  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [16]:
p,n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V, axes=[[0,2], [0,1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [20]:
arr = np.ones((16,16))
k = 4
block_sum = np.add.reduceat(
    np.add.reduceat(arr, np.arange(0, arr.shape[0], k), axis=0), 
    np.arange(0, arr.shape[1],k), axis=1)
block_sum

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [25]:
def iterate(arr):
    # count neighbours
    N = (arr[0:-2, 0:-2] + arr[0:-2, 1:-1] + arr[0:-2, 2:] + 
        arr[1:-1, 0:-2] + arr[1:-1, 2:] + 
        arr[2:, 0:-2] + arr[2:, 1:-1] + arr[2:, 2:])

    # Apply rule
    birth = (N==3) & (arr[1:-1, 1:-1] == 0)
    survive = ((N==2) | (N==3)) & (arr[1:-1, 1:-1]==1)
    arr[...] = 0
    arr[1:-1, 1:-1][birth | survive] = 1
    return arr

arr = np.random.randint(0,2,(50,50))

for i in range(100): 
    arr = iterate(arr)

print(arr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [26]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

# Slow
print(arr[np.argsort(arr)[-n:]])

# Fast
print(arr[np.argpartition(-arr, n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9996 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [3]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T 

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    
    return ix

print(cartesian(([1,2,3], [4,5], [6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [4]:
arr = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])

record_arr = np.core.records.fromarrays(arr.T, names='col1, col2, col3', formats="S8, f8, i8")

record_arr

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [22]:
z = np.random.rand(int(5e7))

%timeit np.power(z,3)
%timeit z*z*z
%timeit np.einsum('i, i, i->i', z,z,z)

1.56 s ± 222 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
251 ms ± 18.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
190 ms ± 4.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [6]:
A = np.random.randint(0,5, (8,3))
B = np.random.randint(0,5, (2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([0, 1, 2, 3, 5, 6, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [9]:
arr = np.random.randint(0,5,(10,3))
print("original array\n",arr)

x = np.all(arr[:,1:] == arr[:, :-1], axis=1)
y = arr[~x]
print("Array with extracted unequal values\n",y)



original array
 [[2 1 0]
 [1 2 1]
 [4 3 2]
 [1 0 3]
 [0 2 4]
 [4 0 4]
 [0 1 3]
 [1 2 1]
 [1 0 1]
 [3 4 2]]
Array with extracted unequal values
 [[2 1 0]
 [1 2 1]
 [4 3 2]
 [1 0 3]
 [0 2 4]
 [4 0 4]
 [0 1 3]
 [1 2 1]
 [1 0 1]
 [3 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [11]:
x = np.array([0,1,2,3,15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [13]:
arr = np.random.randint(0,2, (6,3))
U = np.ascontiguousarray(arr).view(np.dtype((np.void, arr.dtype.itemsize * arr.shape[1])))
_, idx = np.unique(U, return_index=True)
unique_rows = arr[idx]
print(unique_rows)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [14]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum("i->", A) # np.sum(A)
np.einsum("i, i->i", A,B) # A * B
np.einsum("i,i", A, B) # np.inner(A, B)
np.einsum("i, j->ij", A, B) # np.outer(A,B)

array([[0.00409315, 0.31935257, 0.30984196, 0.29961966, 0.5013219 ,
        0.66330157, 0.64643751, 0.56128046, 0.03742786, 0.57086588],
       [0.00377524, 0.29454857, 0.28577665, 0.27634831, 0.46238441,
        0.61178319, 0.59622895, 0.51768601, 0.03452085, 0.52652695],
       [0.00131952, 0.10295071, 0.09988475, 0.09658935, 0.16161275,
        0.21383065, 0.20839413, 0.18094178, 0.01206574, 0.18403186],
       [0.00194879, 0.15204678, 0.14751869, 0.14265175, 0.2386841 ,
        0.31580416, 0.30777502, 0.26723094, 0.01781976, 0.27179465],
       [0.00304448, 0.23753392, 0.23045995, 0.22285661, 0.37288241,
        0.49336263, 0.48081917, 0.41747949, 0.02783878, 0.42460912],
       [0.00252479, 0.19698717, 0.19112071, 0.18481526, 0.30923184,
        0.40914623, 0.39874392, 0.34621625, 0.02308673, 0.35212886],
       [0.00115978, 0.09048741, 0.08779261, 0.08489616, 0.14204777,
        0.18794413, 0.18316576, 0.15903681, 0.01060505, 0.16175281],
       [0.00152235, 0.11877526, 0.1152380

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [16]:
z = np.arange(0, 10*np.pi, 0.1)
n = 1

X = n * z * np.cos(z)
Y = n * z * np.sin(z)

segment_length = (np.diff(X) ** 2 + np.diff(Y) ** 2) ** .5
r = np.zeros_like(X)
r[1:] = np.cumsum(segment_length) # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path

# integer path
x_int = np.interp(r_int, r, X)
print("X_int\n", x_int)
y_int = np.interp(r_int, r, Y)
print("Y_int\n", y_int)

X_int
 [ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [17]:
X = np.asanyarray([[1.0, 0.0, 3.0, 8.0],
                    [2.0, 0.0, 1.0, 1.0],
                    [1.5, 2.5, 1.0, 0.0]])

n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [19]:
# Create random 1D array
X = np.random.randn(100)

# number of bootstrap samples
N = 1000

idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
percentile_mean = np.percentile(means, [2.5, 97.5])
percentile_mean

array([-0.17015332,  0.21518303])